services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:80"
    # Ці змінні будуть прочитані з файлу .env і передані в запущений контейнер
    environment:
      DISABLE_HTTPS: "true"
      VITE_API_URL: ${VITE_API_URL}
      VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID}
      VITE_STRIPE_PUBLISHABLE_KEY: ${VITE_STRIPE_PUBLISHABLE_KEY}