const API_URL = import.meta.env.VITE_API_URL;
const GOOGLE_CLIENT_ID = import.meta.env.VITE_GOOGLE_CLIENT_ID;
const STRIPE_PUBLISHABLE_KEY = import.meta.env.VITE_STRIPE_PUBLISHABLE_KEY;

const APP_ENV = {
  API_URL: API_URL,
  GOOGLE_CLIENT_ID: GOOGLE_CLIENT_ID,
  STRIPE_PUBLISHABLE_KEY: STRIPE_PUBLISHABLE_KEY,
};

export default APP_ENV;
